// Copies a selection of Material Icon Theme's file and folder icons into public/file-icons/ (with the theme's LICENSE)
// and writes their name map to src/app/core/icons/file-icon-map.ts (docs/ARCHITECTURE.md, "Frontend"). Both are
// committed, so builds and tests never need the package. Run it after changing ALLOWED or updating the package:
// node scripts/file-icons.mjs (README.md, "Updating the file icons").
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const WEB = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const PACKAGE = path.join(WEB, 'node_modules', 'material-icon-theme');
const MANIFEST = path.join(PACKAGE, 'dist', 'material-icons.json');
const OUT = path.join(WEB, 'public', 'file-icons');
const MAP = path.join(WEB, 'src', 'app', 'core', 'icons', 'file-icon-map.ts');

/** The theme's defaults: any file, any folder (closed and open), the root folder. */
const DEFAULTS = ['file', 'folder', 'folder-open', 'folder-root', 'folder-root-open'];

/**
 * The icons the portal ships, by the theme's icon names; a folder icon brings its "-open" variant. The theme's logos of
 * AI tools stay out (the interface carries no such branding): their files fall back to the extension's icon.
 */
const ALLOWED = [
  // files
  'angular', 'c', 'certificate', 'cmake', 'console', 'cpp', 'csharp', 'css', 'database', 'diff', 'docker', 'document',
  'editorconfig', 'eslint', 'font', 'git', 'go', 'gradle', 'h', 'hex', 'html', 'http', 'image', 'java',
  'javascript', 'json', 'key', 'less', 'license', 'lock', 'log', 'makefile', 'markdown', 'maven', 'nodejs', 'npm', 'pdf',
  'playwright', 'pnpm', 'prettier', 'python', 'react', 'react_ts', 'readme', 'rust', 'sass', 'settings', 'svg',
  'test-ts', 'toml', 'tsconfig', 'typescript', 'visualstudio', 'vite', 'vitest', 'vue', 'xml', 'yaml', 'zip',
  // folders
  'folder-api', 'folder-app', 'folder-class', 'folder-client', 'folder-components', 'folder-config', 'folder-controller',
  'folder-core', 'folder-coverage', 'folder-css', 'folder-database', 'folder-dist', 'folder-docker', 'folder-docs',
  'folder-features', 'folder-git', 'folder-github', 'folder-home', 'folder-images', 'folder-java', 'folder-lib',
  'folder-migrations', 'folder-mock', 'folder-node', 'folder-public', 'folder-repository', 'folder-resource',
  'folder-scripts', 'folder-server', 'folder-shared', 'folder-src', 'folder-target', 'folder-temp', 'folder-test',
  'folder-tools', 'folder-utils', 'folder-views', 'folder-vscode'
];

const manifest = JSON.parse(fs.readFileSync(MANIFEST, 'utf8'));
const { version } = JSON.parse(fs.readFileSync(path.join(PACKAGE, 'package.json'), 'utf8'));
const allowed = new Set(ALLOWED);
const folders = ALLOWED.filter((name) => name.startsWith('folder-'));
const icons = [...DEFAULTS, ...ALLOWED, ...folders.map((name) => `${name}-open`)];
const missing = icons.filter((name) => !Object.hasOwn(manifest.iconDefinitions, name));
if (missing.length > 0) {
  console.error(`Not icons of material-icon-theme ${version}: ${missing.join(', ')}`);
  process.exit(1);
}

/** The manifest's entries whose icon is allowed, with lower-case keys, in a stable order. */
function pick(map) {
  return Object.fromEntries(
    Object.entries(map ?? {})
      .filter(([, icon]) => allowed.has(icon))
      .map(([key, icon]) => [key.toLowerCase(), icon])
      .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
  );
}

fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(OUT, { recursive: true });
for (const name of icons) {
  const source = path.resolve(path.dirname(MANIFEST), manifest.iconDefinitions[name].iconPath);
  if (!source.endsWith('.svg')) {
    console.error(`${name}: not an SVG (${source})`);
    process.exit(1);
  }
  fs.copyFileSync(source, path.join(OUT, `${name}.svg`));
}
fs.copyFileSync(path.join(PACKAGE, 'LICENSE'), path.join(OUT, 'LICENSE'));

const declaration = (name, comment, entries) =>
  `/** ${comment} */\nexport const ${name}: Readonly<Record<string, string>> = ${JSON.stringify(entries, null, 2)};\n`;
fs.writeFileSync(
  MAP,
  [
    `// Generated by web/scripts/file-icons.mjs from material-icon-theme ${version} (MIT). Do not edit by hand.`,
    '',
    declaration('FILE_NAMES', 'Whole file names (lower case) → icon.', pick(manifest.fileNames)),
    declaration('FILE_EXTENSIONS', 'Suffixes after a dot (lower case) → icon.', pick(manifest.fileExtensions)),
    declaration('FOLDER_NAMES', 'Folder names (lower case) → icon; an expanded folder adds "-open".', pick(manifest.folderNames))
  ].join('\n')
);
console.log(`${icons.length} icons in public/file-icons; the map in src/app/core/icons/file-icon-map.ts`);
